"""Representative Colorado residential load profiles (packaged reference data).

Unlike the PVWatts and URDB loaders, these are *static* reference profiles (not
per-request API queries), so they are packaged as committed CSVs and read with no
network. Provenance and derivation are documented in profiles/SOURCE.md and
regenerated by scripts/make_resstock_profiles.py.

Profiles are bucketed by (season, day type): summer/winter x weekday/weekend, 4
committed files. The public API is keyed by ``(month, day_type)`` — an internal
month->season fold maps the 12 months onto the 2 season buckets — so call sites
stay unchanged if this later grows to 12 monthly buckets.
"""

from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

_PROFILES_DIR = Path(__file__).resolve().parent / "profiles"

# Season split pinned to the Xcel RE-TOU tariff: summer = Jun-Sep (0-based months
# 5..8), winter = the rest. Must match scripts/make_resstock_profiles.py and the
# price season so load and price never disagree.
_SUMMER_MONTHS0 = frozenset({5, 6, 7, 8})


def _season(month: int) -> str:
    if not 0 <= month <= 11:
        raise ValueError(f"month must be 0-based in 0..11, got {month}")
    return "summer" if month in _SUMMER_MONTHS0 else "winter"


def _read_profile(name: str) -> np.ndarray:
    with open(_PROFILES_DIR / name, newline="") as f:
        reader = csv.DictReader(f)
        return np.array([float(row["load_kwh"]) for row in reader], dtype=float)


def load_profile(month: int, day_type: str) -> np.ndarray:
    """Representative CO residential load: 24 hourly kWh for ``(month, day_type)``.

    ``month`` is 0-based (0=Jan .. 11=Dec); ``day_type`` is ``"weekday"`` or
    ``"weekend"``. Pair with :mod:`quantum_solar.data.calendar` to key an annual
    loop: ``load_profile(day_to_month(d), day_type(d))``.

    ENERGY quantity (kWh): aggregate to slots with :func:`~.nrel.to_slots` (which
    SUMS), never :func:`~.nrel.price_to_slots` (which averages).

    Currently folds all 12 months onto 2 season buckets (summer = Jun-Sep). The
    ``month`` key is deliberate: swapping in 12 monthly buckets later is a data +
    fold change with no call-site churn.

    Source: NREL End-Use Load Profiles / ResStock (``resstock_amy2018_release_2``),
    Colorado single-family-detached aggregate, per-dwelling. See ``profiles/SOURCE.md``.
    """
    if day_type not in ("weekday", "weekend"):
        raise ValueError(f"day_type must be 'weekday' or 'weekend', got {day_type!r}")
    return _read_profile(f"co_residential_{_season(month)}_{day_type}.csv")


def co_summer_weekday_load() -> np.ndarray:
    """Back-compat alias: the summer-weekday profile (July weekday -> summer bucket).

    Prefer :func:`load_profile`. Retained for existing call sites and tests.
    """
    return load_profile(6, "weekday")
