"""Generate the IBM Quantum job-provenance table from the committed artifacts.

Every hardware result in this repo traces to a job ID on a named backend. That
provenance is currently spread across six `hardware_counts*.json` files and is
invisible unless you open them, so this collects it into one table.

Generated, never hand-edited: a provenance table that is transcribed by hand is a
claim that goes stale the moment another job runs (docs/LESSONS.md section 7).
Re-run this after any hardware job and commit the result.

Usage:
    python scripts/hardware_jobs.py            # print the table
    python scripts/hardware_jobs.py --write    # write docs/results/hardware-jobs.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

RESULTS = Path(__file__).resolve().parent.parent / "docs" / "results"
OUT = RESULTS / "hardware-jobs.md"

# (counts file, label, first-committed date, what the run was for, write-up).
# The label is explicit rather than derived from the filename: str.strip() takes a
# character set, not a suffix, so the obvious one-liner turned "slackfree" into
# "lackfree".
RUNS = [
    ("hardware_counts.json", "first", "2026-07-11",
     "First hardware run: four circuits, two sizes, two depths.",
     "hardware-run-encoding.md"),
    ("hardware_counts_slackfree.json", "slackfree", "2026-08-03",
     "Slack-free encoding vs the exact encoding, with and without error "
     "mitigation.",
     "hardware-run-encoding.md"),
    ("hardware_counts_replication.json", "replication", "2026-08-03",
     "Replication of the encoding gap, plus a default-weight control.",
     "hardware-run-encoding-replication.md"),
    ("hardware_counts_spread.json", "spread", "2026-08-03",
     "Run-to-run spread at n=10 replicates, powered so RESOLVED was reachable.",
     "hardware-run-spread.md"),
    ("hardware_counts_depth.json", "depth", "2026-08-25",
     "Does depth help, net of noise? cp3 at reps 1 and 2 in one job.",
     "hardware-run-depth.md"),
    ("hardware_counts_depth_replication.json", "depth-replication", "2026-08-26",
     "Replication of the depth result, identical angles, new calibration window.",
     "hardware-run-depth-replication.md"),
]


def load(name):
    d = json.loads((RESULTS / name).read_text())
    ids = d.get("job_ids", d.get("job_id"))
    ids = [ids] if isinstance(ids, str) else list(ids or [])
    results = d.get("results", [])
    shots = sum(r.get("shots") or d.get("shots") or 0 for r in results)
    cal = d.get("backend_calibration") or {}
    return {
        "backend": d.get("backend"), "job_ids": ids, "circuits": len(results),
        "shots": shots, "qpu_s": d.get("actual_qpu_seconds") or 0,
        "cal_date": cal.get("last_update_date"),
        "err_2q": cal.get("median_2q_gate_error"),
        "err_ro": cal.get("median_readout_error"),
    }


def build() -> str:
    rows = [(lab, d, p, w, load(n)) for n, lab, d, p, w in RUNS]
    tot_j = sum(len(r[4]["job_ids"]) for r in rows)
    tot_c = sum(r[4]["circuits"] for r in rows)
    tot_s = sum(r[4]["shots"] for r in rows)
    tot_q = sum(r[4]["qpu_s"] for r in rows)
    backends = sorted({r[4]["backend"] for r in rows})

    L = ["# IBM Quantum jobs behind every hardware result",
         "",
         "<!-- GENERATED by scripts/hardware_jobs.py -- do not edit by hand. -->",
         "",
         f"**{tot_j} jobs, {tot_c} circuits, {tot_s:,} shots, {tot_q:.0f} seconds "
         f"of QPU time on {', '.join(backends)}.**",
         "",
         "Every number in the hardware write-ups traces to one of these job IDs.",
         "They are listed so a reader can see the runs were real, small, and few "
         "— and because the most useful decision in the project was *declining* "
         "to spend more (docs/LESSONS.md section 9).",
         ""]

    L += ["| run | date | job ID(s) | circuits | shots | QPU s | write-up |",
          "|---|---|---|---:|---:|---:|---|"]
    for lab, date, _purpose, doc, d in rows:
        ids = "<br>".join(f"`{j}`" for j in d["job_ids"])
        L.append(f"| `{lab}` "
                 f"| {date} | {ids} | {d['circuits']} | {d['shots']:,} "
                 f"| {d['qpu_s']:.0f} | [{doc}]({doc}) |")
    L += ["", "## What each run was for", ""]
    for lab, date, purpose, doc, d in rows:
        L.append(f"- **{date}** — {purpose} "
                 f"({d['circuits']} circuits, {d['qpu_s']:.0f} s QPU) "
                 f"→ [{doc}]({doc})")

    L += ["", "## Device calibration as recorded at submission", "",
          "| run | backend | median 2q gate error | median readout error | "
          "calibration timestamp |", "|---|---|---:|---:|---|"]
    for lab, date, _p, _doc, d in rows:
        if d["cal_date"] is None:
            L.append(f"| {date} | {d['backend']} | not recorded | not recorded | "
                     "not recorded |")
        else:
            L.append(f"| {date} | {d['backend']} | {d['err_2q']:.4%} "
                     f"| {d['err_ro']:.4%} | {d['cal_date']} |")
    L += ["",
          "The first run predates calibration capture; it was added after, which "
          "is why device drift could not be ruled out retrospectively for it "
          "(docs/LESSONS.md section 8).",
          "",
          "## Reproducing",
          "",
          "```bash",
          "pip install -r requirements-hardware.txt   # qiskit-ibm-runtime",
          "python scripts/experiment_hardware.py --help",
          "```",
          "",
          "Auth is a saved account (`~/.qiskit`) via a bare `QiskitRuntimeService()`.",
          "The submit stage has a dry-run mode; use it. It once caught the script "
          "rebuilding the *previous* experiment's circuits, which would have burned "
          "QPU time re-answering a settled question (docs/LESSONS.md section 6).",
          ""]
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help=f"write {OUT}")
    args = ap.parse_args()
    text = build()
    if args.write:
        OUT.write_text(text)
        print(f"wrote {OUT}")
    else:
        print(text)


if __name__ == "__main__":
    main()
