"""Does the selection rule replicate on fresh instances?

Pre-registered in ``docs/plans/selection-rule-replication.md`` — read that first. The
instances, the band, and all three predictions are fixed there.

Simulator and exact computation only. No QPU. Scores distributions already computed by
``basin_study_reps2.py --instance N --tag iN``; re-runs in seconds.

    python scripts/selection_rule_replication.py
"""

from __future__ import annotations

import json
import subprocess
import sys
import warnings
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

warnings.filterwarnings("ignore")

import experiment_hardware as hw  # noqa: E402
import selection_rule_study as base  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "docs" / "results"
PLAN = ROOT / "docs" / "plans" / "selection-rule-replication.md"

BAR = 5 / 2**6
FRESH_INSTANCES = (4, 5, 6)          # never used in any prior study here
BAND_MAX_ALPHA = 0.03                # the "sound and reproducible" cut, fixed in advance
ARGMAX_FLOOR = 0.80                  # P1's registered floor


def require_registered() -> str:
    if not PLAN.exists():
        raise SystemExit(f"REFUSING TO RUN: {PLAN.relative_to(ROOT)} does not exist.")
    out = subprocess.run(("git", "-C", str(ROOT), "log", "--format=%H", "-1", "--", str(PLAN)),
                         capture_output=True, text=True).stdout.strip()
    if not out:
        raise SystemExit("REFUSING TO RUN: the pre-registration is not committed.")
    if subprocess.run(("git", "-C", str(ROOT), "status", "--porcelain", "--", str(PLAN)),
                      capture_output=True, text=True).stdout.strip():
        raise SystemExit("REFUSING TO RUN: the pre-registration has uncommitted edits.")
    return out


def cells():
    for instance in FRESH_INSTANCES:
        path = RESULTS / f"basin_distributions_reps2_i{instance}.npz"
        if not path.exists():
            raise SystemExit(f"REFUSING TO RUN: {path.relative_to(ROOT)} is missing; "
                             f"sweep instance {instance} first.")
        store = np.load(path)
        for alpha in sorted({float(k.split("_")[0][1:]) for k in store.files}):
            problem, qubo, _ = hw.build_target(3, instance, 2,
                                               encoding="checkpoint3", alpha=alpha)
            opt_mask, feas_mask = hw.basis_masks(problem, qubo)
            X = hw.enumerate_bitstrings(qubo.num_vars).astype(float)
            energies = np.einsum("bi,ij,bj->b", X, qubo.Q, X) + qubo.offset
            qubo_min = np.flatnonzero(np.isclose(energies, energies.min()))
            masses = store[f"a{alpha}_m"]
            dists = store[f"a{alpha}_d"]

            scored = {}
            for name, score in base.rules(feas_mask, energies).items():
                values = np.array([score(p) for p in dists])
                pick = int(np.argmax(values))
                scored[name] = {
                    "picked_seed": pick + 1,
                    "picked_mass": float(masses[pick]),
                    "picked_clears": bool(masses[pick] >= BAR),
                    "picked_is_argmax": bool(
                        abs(masses[pick] - masses.max()) < 1e-12),
                }
            yield {
                "instance": instance, "alpha": alpha,
                "sound": bool(feas_mask[qubo_min].all() and opt_mask[qubo_min].any()),
                "in_band": alpha <= BAND_MAX_ALPHA,
                "any_clears": bool((masses >= BAR).any()),
                "best_mass": float(masses.max()),
                "rules": scored,
            }


def main():
    commit = require_registered()
    print(f"Pre-registration committed at {commit[:12]} — proceeding.")
    records = list(cells())

    band = [c for c in records if c["sound"] and c["in_band"]]
    argmax = sum(1 for c in band if c["rules"]["feasible_mass"]["picked_is_argmax"])
    wins = sum(1 for c in band
               if c["rules"]["feasible_mass"]["picked_mass"] > c["rules"]["lowest_H"]["picked_mass"])
    losses = sum(1 for c in band
                 if c["rules"]["feasible_mass"]["picked_mass"] < c["rules"]["lowest_H"]["picked_mass"])

    # P3's stratum: <H> misses the bar but something clears. The discriminating case.
    stratum = [c for c in band if c["any_clears"] and not c["rules"]["lowest_H"]["picked_clears"]]
    found = sum(1 for c in stratum if c["rules"]["feasible_mass"]["picked_clears"])

    result = {
        "_source": "Generated by scripts/selection_rule_replication.py; pre-registered "
                   "in docs/plans/selection-rule-replication.md. Simulator only, no QPU.",
        "plan_commit": commit,
        "fresh_instances": list(FRESH_INSTANCES), "bar": BAR,
        "band_max_alpha": BAND_MAX_ALPHA, "argmax_floor": ARGMAX_FLOOR,
        "band_cells": len(band),
        "verdicts": {
            "P1_argmax_replicates": {
                "argmax_cells": argmax, "of": len(band),
                "fraction": argmax / len(band) if band else None,
                "floor": ARGMAX_FLOOR,
                "falsified": not band or argmax / len(band) < ARGMAX_FLOOR,
            },
            "P2_beats_the_incumbent": {
                "wins": wins, "losses": losses, "ties": len(band) - wins - losses,
                "falsified": losses >= wins,
            },
            "P3_discriminating_cells": {
                "stratum_size": len(stratum),
                "feasible_mass_clears": found,
                "estimable": bool(stratum),
                "falsified": bool(stratum) and found <= len(stratum) / 2,
                "note": None if stratum else
                        "not estimable: no cell where <H> misses the bar while some "
                        "tuning clears. The fresh instances are easy, exactly as the "
                        "plan warned could happen; this is no discriminating evidence, "
                        "not support.",
            },
        },
        "cells": records,
    }
    (RESULTS / "selection_rule_replication.json").write_text(json.dumps(result, indent=1) + "\n")

    print(f"\nband: {len(band)} sound cells at alpha <= {BAND_MAX_ALPHA} "
          f"across instances {FRESH_INSTANCES}")
    for name, v in result["verdicts"].items():
        state = "FALSIFIED" if v["falsified"] else ("not estimable"
                if name.startswith("P3") and not v.get("estimable") else "held")
        print(f"  {name}: {state}  {v}")
    print(f"\n{'inst':>5}{'alpha':>8}{'best':>9}{'feas->':>9}{'<H>->':>9}{'argmax?':>9}  clearable")
    for c in band:
        R = c["rules"]
        print(f"{c['instance']:>5}{c['alpha']:>8}{c['best_mass']:>9.4f}"
              f"{R['feasible_mass']['picked_mass']:>9.4f}{R['lowest_H']['picked_mass']:>9.4f}"
              f"{str(R['feasible_mass']['picked_is_argmax']):>9}  {c['any_clears']}")


if __name__ == "__main__":
    main()
